const events = [
	{
		id: 1,
		title: 'Robo wars',
		description: 'Officia ad cillum commodo minim sint non non dolore laborum aliqua occaecat amet nisi voluptate ut laborum nostrud aute ad irure quis quis reprehenderit sed amet et mollit in commodo aliquip dolor adipisicing exercitation dolore non reprehenderit dolor reprehenderit do exercitation laborum officia cillum qui adipisicing reprehenderit amet mollit officia aute mollit ad do eu deserunt do reprehenderit qui pariatur laborum adipisicing in sed in sint consectetur deserunt cillum excepteur est ut eu nisi cillum tempor cillum nisi nulla elit occaecat deserunt eiusmod quis amet excepteur consectetur id nisi magna incididunt consequat dolor enim incididunt fugiat ad aliquip tempor aliqua et cupidatat cillum veniam sunt esse in dolor aliquip labore adipisicing fugiat nulla velit magna qui reprehenderit laboris sed quis fugiat pariatur ut tempor velit consectetur dolore laboris sed amet dolor incididunt laboris officia ut laborum aliquip labore sunt nisi consequat dolor velit exercitation qui minim reprehenderit quis voluptate aliquip ullamco est veniam cupidatat velit labore culpa amet duis consequat incididunt dolor non quis laboris ex culpa aute ullamco.',
		startingDate: '1 June, 2017 @ 5:00p.m.',
		endDate: '1 June, 2017 @ 6:00p.m.',
		teamsize: 5,
		activityId: 2,
		url: '/events/1',
		backgroundImageUrl: 'http://source.unsplash.com/random',
	},
		{
		id: 2,
		title: 'Robo wars',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		startingDate: '1 June, 2017 @ 5:00p.m.',
		endDate: '1 June, 2017 @ 6:00p.m.',
		teamsize: 5,
		activityId: 2,
		url: '/events/1',
		backgroundImageUrl: 'http://source.unsplash.com/random',
	},
	{
		id: 3,
		title: 'Robo wars',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		startingDate: '1 June, 2017 @ 5:00p.m.',
		endDate: '1 June, 2017 @ 6:00p.m.',
		teamsize: 5,
		activityId: 2,
		url: '/events/1',
		backgroundImageUrl: 'http://source.unsplash.com/random',
	},
		{
		id: 4,
		title: 'Robo wars',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		startingDate: '1 June, 2017 @ 5:00p.m.',
		endDate: '1 June, 2017 @ 6:00p.m.',
		teamsize: 5,
		activityId: 2,
		url: '/events/1',
		backgroundImageUrl: 'http://source.unsplash.com/random',
	},
	{
		id: 5,
		title: 'Robo wars',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		startingDate: '1 June, 2017 @ 5:00p.m.',
		endDate: '1 June, 2017 @ 6:00p.m.',
		teamsize: 5,
		activityId: 2,
		url: '/events/1',
		backgroundImageUrl: 'http://source.unsplash.com/random',
	},
	{
		id: 6,
		title: 'Robo wars',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		startingDate: '1 June, 2017 @ 5:00p.m.',
		endDate: '1 June, 2017 @ 6:00p.m.',
		teamsize: 5,
		activityId: 2,
		url: '/events/1',
		backgroundImageUrl: 'http://source.unsplash.com/random',
	},
		{
		id: 7,
		title: 'Robo wars',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		startingDate: '1 June, 2017 @ 5:00p.m.',
		endDate: '1 June, 2017 @ 6:00p.m.',
		teamsize: 5,
		activityId: 2,
		url: '/events/1',
		backgroundImageUrl: 'http://source.unsplash.com/random',
	},
	{
		id: 8,
		title: 'Robo wars',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		startingDate: '1 June, 2017 @ 5:00p.m.',
		endDate: '1 June, 2017 @ 6:00p.m.',
		teamsize: 5,
		activityId: 2,
		url: '/events/1',
		backgroundImageUrl: 'http://source.unsplash.com/random',
	},
	{
		id: 9,
		title: 'Robo wars',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		startingDate: '1 June, 2017 @ 5:00p.m.',
		endDate: '1 June, 2017 @ 6:00p.m.',
		teamsize: 5,
		activityId: 2,
		url: '/events/1',
		backgroundImageUrl: 'http://source.unsplash.com/random',
	},
	{
		id: 10,
		title: 'Robo wars',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		startingDate: '1 June, 2017 @ 5:00p.m.',
		endDate: '1 June, 2017 @ 6:00p.m.',
		teamsize: 5,
		activityId: 2,
		url: '/events/1',
		backgroundImageUrl: 'http://source.unsplash.com/random',
	},
	{
		id: 11,
		title: 'Robo wars',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		startingDate: '1 June, 2017 @ 5:00p.m.',
		endDate: '1 June, 2017 @ 6:00p.m.',
		teamsize: 5,
		activityId: 2,
		url: '/events/1',
		backgroundImageUrl: 'http://source.unsplash.com/random',
	},
	{
		id: 12,
		title: 'Robo wars',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		startingDate: '1 June, 2017 @ 5:00p.m.',
		endDate: '1 June, 2017 @ 6:00p.m.',
		teamsize: 5,
		activityId: 2,
		url: '/events/1',
		backgroundImageUrl: 'http://source.unsplash.com/random',
	},
]

const activities = [
	{
		id: 1,
		title: 'Cultural',
		imageUrl: 'Images/cover1.jpg',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
	},
	{
		id: 2,
		title: 'Technical',
		imageUrl: 'Images/cover2.jpg',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
	},
	{
		id: 3,
		title: 'Lectures',
		imageUrl: 'Images/cover3.jpg',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
	},
	{
		id: 4,
		title: 'Workshops',
		imageUrl: 'Images/cover4.jpg',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
	},
	{
		id: 5,
		title: 'Shows',
		imageUrl: 'Images/cover5.jpg',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
	}
]

export { events, activities };